// <auto-generated />
namespace SmartHomeEnergySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class izmereneVrednostiPanela2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(izmereneVrednostiPanela2));
        
        string IMigrationMetadata.Id
        {
            get { return "202006051118405_izmereneVrednostiPanela2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
